In [2]:
import numpy as np

In [7]:
#72. How to swap two rows of an array?

a = np.array([[0,0,0],[1,1,1],[2,2,2]])
print(a)
a[[0,2]]=a[[2,0]]
print(a)

[[0 0 0]
 [1 1 1]
 [2 2 2]]
[[2 2 2]
 [1 1 1]
 [0 0 0]]


In [8]:
#75. How to compute averages using a sliding window over an array?

a = np.array([[1,2,3], [4,5,6]])
print(a)
print(np.cumsum(a, axis = 0))
print(np.cumsum(a, axis = 1))

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [5 7 9]]
[[ 1  3  6]
 [ 4  9 15]]
